### PR TITLE
color_normalization: Add unit tests and do PEP 8 renaming

### PR DESCRIPTION
**Pull request by cdeepakroy**
Also added a utility function `histomicstk/preprocessing/color_conversion/compute_lab_mean_std` to compute the mean and stddev of an RGB image in LAB space. These are needed as input for reinhard normalization.

### CODE REVIEW

**Comment by cdeepakroy** [comment]
@cooperlab Can you please take a look?

**Comment by cooperlab** [comment]
LGTM - my only comment is that 'compute_lab_mean_std' is a bit long.

**Comment by cdeepakroy** [comment]
What would you suggest? Below are other alternatives:
* `lab_mean_std`
* `compute_lab_stats`

**Comment by cooperlab** [comment]
'lab_mean_std' - I don't have a strong preference though. Don't change it if it's a PITA.

**Pull request merged**
