### PR TITLE
Update girder version to fix installation

### PR DESCRIPTION
**Pull request by zachmullen**
This was a breakage in an upstream npm package related to fetching our fontello icon set.

### CODE REVIEW

**Comment by zachmullen** [comment]
The `server_HistomicsTK.docker` test is failing due to timeouts, any idea what's going wrong there?

**Comment by manthey** [comment]
I'm getting the same failure locally.  I'll look into it.

**Comment by manthey** [comment]
The failure is caused by how we check if a job is updated.  Before, whenever a job was updated, save was called on the job model, and girder emitted `model.job.save` and `model.job.save.after` events.  Now, no such events are emitted.  Instead of hooking to these, we can bind to the `jobs.job.update` event.  Strictly, this event is only emitted when update is called via a REST endpoint (and not via the `updateJob` method), so this is not friendly to clients that don't use rest.

I can change the event that is bound, but it might also be desirable to refactor the jobs plugin to either (a) emit the `jobs.job.update` event regardless of update code path, and / or (b) emit the `model.job.save` and `model.job.save.after` events on updates.

**Comment by zachmullen** [comment]
Ah, I see. Would it be suitable to just move the emission of `jobs.job.update` into the model layer rather than the REST layer?

**Comment by manthey** [comment]
Yes, along with the `defaultPrevented` code that is also in the REST layer.

**Comment by zachmullen** [comment]
Roger, I'll do that now.

**Comment by manthey** [comment]
From a utility perspective, it would be nice to have a `jobs.job.update.after` event, too, so that a client that just wants the current state of the job doesn't have to combine the update parameters with the current job status.

**Comment by zachmullen** [comment]
The tricky part here is that, unlike with most of our model layer events, we don't necessarily have the complete document available for these events, since part of this optimization was that we don't fetch or push the full document. So long as downstream handlers for this event understand that constraint, we should be fine.

**Comment by zachmullen** [comment]
(At the moment, it's only the `log` field that might not be accurate.)

**Comment by manthey** [comment]
Primarily, if there is an event which is sure to have the current job status, I think that would satisfy most client's requirements.

**Comment by zachmullen** [comment]
Your changes LGTM, merge if you are OK with this in general.

**Pull request merged**
