### PR TITLE
Update CondenseLabel.py

### PR DESCRIPTION
**Pull request by cooperlab**
Fixed zero-offset issue in filling new values.

### CODE REVIEW

**Comment by cdeepakroy** [comment]
@manthey Can you please look into this [error](https://travis-ci.org/DigitalSlideArchive/HistomicsTK/builds/143790060#L2567)? 

The test was passing with several earlier PRs . Furthermore, this PR does not touch any files related to the test that is failing.

**Comment by manthey** [comment]
@cdeepakroy Sometimes travis's build cache gets something erroneous stuck in it.  I've cleared the travis build cache to see if this helps.  If not, I'll look further.

**Comment by manthey** [comment]
There is a PIL error:
`ImportError: /home/travis/build/DigitalSlideArchive/HistomicsTK/build/miniconda/lib/python2.7/site-packages/PIL/_imaging.so: undefined symbol: PyUnicodeUCS2_AsLatin1String`
So we must have changed versions from conda in some way.

**Comment by manthey** [comment]
A few days ago, conda made the default Pillow version 3.3.0 (before it was 3.2.0).  This means that Conda now installs Pillow 3.3.0, then we pip uninstall that and install version 3.2.0, and the pip version doesn't work properly in our environment.

**Comment by manthey** [comment]
@cdeepakroy See PR #122 for the fix to the travis problem.

**Pull request merged**
