### PR TITLE
Convert to using Girder for testing

### PR DESCRIPTION
**Pull request by brianhelba**

### CODE REVIEW

**Comment by brianhelba** [comment]
This works, but it's way too slow to build all the Python prereqs (numpy, scipy, etc.).

I'm going to switch it to use Miniconda.

**Comment by cdeepakroy** [comment]
@brianhelba was facing the same issue today and stumbled on a similar [solution](http://lmjohns3.com/2015/06/using-travis-ci-with-miniconda-scipy-and-nose.html).

**Comment by brianhelba** [comment]
Yup, that is pretty similar to what I have.

**Comment by cdeepakroy** [comment]
@brianhelba should i merge this and proceed?

**Comment by brianhelba** [comment]
I still need to update the Travis script to install Romanesco.

We *could* merge it now, as the build succeeds, it's just the tests that fail: style tests are failing for obvious reasons, and the functional tests fail because of a missing Romansco.

**Comment by brianhelba** [comment]
I've just updated this to add Romanesco. Let's see how it goes.

I'll merge once it's stable.

**Comment by brianhelba** [comment]
Merged.

**Comment by cdeepakroy** [comment]
@brianhelba do you think it would be a good idea to put the tests for the rest end points and the actual toolkit in separate folders? Or put everything in the plugin_tests folder?

**Pull request merged**
