### PR TITLE
Add positive pixel count example

### PR DESCRIPTION
**Pull request by neal-siekierski**
This PR adds examples of the use of the new `histomicstk.segmentation.positive_pixel_count` module as well as the CLI. Feedback is welcome for the writing, the particular examples given (I didn't spend that much time trying to find good parameter values), or anything else you may think of.

### CODE REVIEW

**Comment by cdeepakroy** [comment]
@cooperlab Can you please take a look at this when you can? Maybe we should use a DAB image instead.

**Comment by cooperlab** [comment]
@cdeepakroy @neal-siekierski I think we should use DAB - do you have an example or do you need one?

**Comment by cdeepakroy** [comment]
Yes, can you please send Neal a DAB example to use?

**Comment by neal-siekierski** [comment]
@cooperlab Any other thoughts?

**Pull request merged**
