### PR TITLE
Use slicer_cli for REST end point generation and docker caching

### PR DESCRIPTION
**Pull request by cdeepakroy**
Me and @salamb recently moved the functionality for automatic REST end point genenration and docker image caching and management into a [girder/slicer_cli](https://github.com/girder/slicer_cli/pull/1) so it can be used by other projects.

This PR, removes that functionality from HistomicsTK and uses slicer_cli for it.

### CODE REVIEW

**Comment by cdeepakroy** [comment]
@manthey Do you know why could the docker_test time out? The exact same test passes [here](https://github.com/girder/slicer_cli_web/blob/master/plugin_tests/docker_test.py) in `girder/slicer_cli_web`.

**Comment by manthey** [comment]
There was a change to how girder jobs are logged, which required a change to how we handle updates.  The same change that was made in PR #183 needs to be made in the girder/slicer_cli_web repository.  I'll take care of it shortly.

**Comment by cdeepakroy** [comment]
Ah! I see! Drop me a message here once you fix it. Thanks!

**Comment by manthey** [comment]
@cdeepakroy I've got a PR in slicer_cli_web to fix the problem.

**Comment by cdeepakroy** [comment]
@manthey Can you take a look? I made the changes but it is still failing.

**Comment by manthey** [comment]
@cdeepakroy I think that it was just the name of the job had changed and needed updating.  With that change it passes on my local machine.

**Comment by manthey** [comment]
This now LGTM.

**Comment by cdeepakroy** [comment]
Thanks!

**Pull request merged**
