### PR TITLE
Add girder_client to setup.py

### LINKED ISSUE #867: Add girder_client to requirements
Many HistomicsTK functions now depend on girder_client. Import fails after pip install on a fresh system.

### PR DESCRIPTION
**Pull request by kheffah**
Closes #867

### CODE REVIEW

**Comment by manthey** [comment]
Can you remove `girder-client` from `requirements-dev.txt`?  No need to have it in both.

**Comment by kheffah** [comment]
> Can you remove girder-client from requirements-dev.txt? No need to have it in both.

@manthey  OK, I removed it.

**Comment by manthey** [comment]
I'm not sure why CI is failing.  I'll look into it.

**Comment by manthey** [comment]
Something changed in Circle-CI, so fixing CI was a bit more work than expected.  In addition to fixing CI, I've added tests for Python 3.8 and a simple test to ensure that our wheels import successfully.

**Pull request merged**
