### PR TITLE
Initial web client

### PR DESCRIPTION
**Pull request by jbeezley**
Even though this is not yet a complete implementation, it is probably time to merge this branch in.  The primary intent of the code here is to:
* [parse](https://github.com/DigitalSlideArchive/HistomicsTK/blob/75e9c9cd091e4fe6878156890980140fcec12dee/web_client/js/schema/parser.js) Slicer XML specs
* [generate](https://github.com/DigitalSlideArchive/HistomicsTK/blob/75e9c9cd091e4fe6878156890980140fcec12dee/web_client/js/models/widget.js) intermediate json objects (backbone models)
* create a series of [panels](https://github.com/DigitalSlideArchive/HistomicsTK/blob/75e9c9cd091e4fe6878156890980140fcec12dee/web_client/js/views/controlsPanel.js) each containing multiple [control widgets](https://github.com/DigitalSlideArchive/HistomicsTK/blob/75e9c9cd091e4fe6878156890980140fcec12dee/web_client/js/views/controlWidget.js), supporting:
  * live updating of their respective models
  * data validation

All of that is implemented and tested with close to complete coverage.  There is other code in here to provide minimal infrastructure that remains untested.

Since I last demoed this to others, I have added a page that renders a more complete example of the different kind of widgets you can create.  This is currently hard coded to display at `/histomicstk#demo`.  The json it is rendering is stored in the repo [here](https://github.com/DigitalSlideArchive/HistomicsTK/blob/75e9c9cd091e4fe6878156890980140fcec12dee/web_client/extra/widget_demo.json).  The spec is roughly equivalent the XML form.

I also made it so the background is rendered with geojs (still cats though).

Things that are missing:
* `Submit` only writes the parameter values to the console when valid rather than running the job
* A few parameter types (notably `directory` for the current analyses)
* Persistence of user provided values (through local storage)

### CODE REVIEW

**Comment by cooperlab** [comment]
Looks good - timing is good as far as I'm concerned.


Lee Cooper, Ph.D.
Assistant Professor of Biomedical Informatics
Assistant Professor of Biomedical Engineering
Emory University School of Medicine - Georgia Institute of Technology
lee.cooper@emory.edu
tel: (404) 712-0110


________________________________

**Comment by cdeepakroy** [comment]
@jbeezley great work! 

You should demo this in the next meeting. Then, we should probably discuss and sketch out how the front-end should look like in the next couple of meetings.

I tried to git checkout your banch and see the front-end through the url `http://localhost:8080/histomicstk#demo` but it doesnt show anything. Am i missing anything?

This is probably coming next. But, your parser doesn't seem to inspect the channel element of the parameter to find whether it is input or output. For output file we have to probably ask for the parent folder in girder and the name of the file.  All non-file outputs will be stored as `key = value` pairs in a `<name>.params` file. If the xml spec has any non-file outputs we have to ask for the name and parent folder of this file in girder too. Also in the parser you could look for the `fileExtensions` attribute of the parameter to filter the files in the file selection widget.

**Comment by jbeezley** [comment]
@cdeepakroy You probably need to rebuild (`npm install` in girder's main directory).

Yes, I'll probably work on the hierarchy widget next to handle input/output as well as image/file/directory distinctions. Non-file outputs will probably need to be handled specially by the girder job.  Possibly, it could find the file somehow and put the parameters into the job model in the database.  We'll have to discuss how to handle it.

**Comment by cdeepakroy** [comment]
@jbeezley i did `npm install` but it still does not show anything. Also updated my girder.

**Comment by cdeepakroy** [comment]
@jbeezley Added large image to HistomicsTK dependencies.

LGTM. Please go ahead and merge this.

**Comment by cdeepakroy** [comment]
Fixes #37

**Pull request merged**
