### PR TITLE
Color normalization / deconvolution debugging

### PR DESCRIPTION
**Pull request by cooperlab**
Performed testing of color normalization and deconvolution methods on several hundred TCGA slides to verify correctness of algorithms. Want to pull this back into the DSA repo to merge with Deepak's recent changes before I move on to segmentation work.

### CODE REVIEW

**Comment by cdeepakroy** [comment]
@cooperlab Since i changed the docstrings to numpy style via this [pull request](https://github.com/DigitalSlideArchive/HistomicsTK/pull/12) so that we can autogenerate the [API documentation](https://histomicstk.readthedocs.org/en/latest/api-docs.html) using sphinx, you will have to fetch those changes and resolve the conflicts which will mostly be at the docstring.

**Comment by cooperlab** [comment]
OK - in that case can you let me know when you will be making broad changes like this that touch many files? It will save work on my end.

-Lee

Lee Cooper, Ph.D.
Assistant Professor of Biomedical Informatics & Biomedical Engineering
Emory University School of Medicine - Georgia Institute of Technology


________________________________

**Comment by cdeepakroy** [comment]
@cooperlab sure. Do you want me to help you with resolving these conflicts?

**Comment by cooperlab** [comment]
No - it's fine. I need to see this stuff to start learning the correct practices.

-Lee

________________________________

**Comment by brianhelba** [comment]
@cooperlab The changes from https://github.com/DigitalSlideArchive/HistomicsTK/pull/16 are going to cause merge conflicts on this branch. You'll need to rebase this branch onto master or merge master into this branch.

Also, go ahead and push your branches directly to "origin" (this repo), instead of [your personal fork](https://github.com/cooperlab/HistomicsTK). That way, if others need to add supplemental commits, we technically can. Of course, etiquette dictates that we'd ask you before doing this.

**Pull request closed without merging**
