### PR TITLE
Fix scrolling in control panels

### PR DESCRIPTION
**Pull request by jbeezley**
This reverts the change in 3794a403, which was intended to fix behavior observed in the demo video... When scrolling on the side panel, the image zooms when reaching a gap in the panels.  

That change had the consequence of disabling scrolling on the side panel entirely.  When attempting to fix this, I found I was unable to reproduce the behavior seen in the video.  If anyone can reproduce it with this change, let me know.

### CODE REVIEW

**Comment by cdeepakroy** [comment]
@jbeezley I just tried it and i was able to reproduce the behavior seen in the demo. If you want, we can do a quick hangout in the afternoon so you can take a look.

**Comment by jbeezley** [comment]
What browser and OS are you using?

**Comment by cdeepakroy** [comment]
I am using
* Google chrome Version 50.0.2661.86 (64-bit)
* Ubuntu 14.04

**Comment by jbeezley** [comment]
I couldn't manage to get Chrome < 51 installed on my Ubuntu 14.04 VM.  The issue didn't occur on chrome 51.0.2704.79.  I think it's either a bug in that particular version of chrome or you have an old stylesheet or jade template cached somewhere.

**Comment by cdeepakroy** [comment]
@zachmullen / @manthey Can you please test it on your machine? If you don't see this problem then something is wrong with my machine.

**Comment by manthey** [comment]
@cdeepakroy I don't see the issue on my machine (Chrome 51, Windows 7).  I'll try another machine, too.

**Comment by manthey** [comment]
Chrome 51, Ubuntu 14.04 works for me properly, too.  I was using a mouse wheel for both Windows and Ubuntu.  I also tried a touchpad and a touch screen on Windows, all without any issue.

**Comment by cdeepakroy** [comment]
Please feel free to merge then.

Maybe something is wrong with my machine then. I will try to figure out why.

**Comment by jbeezley** [comment]
I'm not certain what version of is up at girder.neuro.emory.edu, but as we mentioned in the meeting the bug does exist there.  Modifying the CSS on that site by removing the `pointer-events: none` as is done in this branch seems to fix the issue.  I'll go ahead and merge once the CI tests pass.

**Pull request merged**
