### PR TITLE
Replace SparseColorDeconvolution with SeparateStainsXuSnmf

### PR DESCRIPTION
**Pull request by neal-siekierski**
Since #280, `sparse_color_deconvolution` in `histomicstk.preprocessing.color_deconvolution` has been redundant with a combination of `separate_stains_xu_snmf` and `color_deconvolution`. This PR replaces this routine and the corresponding CLI, `SparseColorDeconvolution`, with routines and CLIs mirroring those around the PCA-based Macenko method.

The import changes made are namely:
- removing `sparse_color_deconvolution`,
- creating a new routine `rgb_separate_stains_xu_snmf` mirroring `rgb_separate_stains_macenko_pca`,
- converting `SparseColorDeconvolution` from a wrapper around `sparse_color_deconvolution` to `SeparateStainsXuSnmf`, a wrapper around `rgb_separate_stains_xu_snmf`, and
- teaching `SeparateStainsXuSnmf` the same extra parameters as `SeparateStainsMacenkoPCA`, namely ones for pixel sampling and Dask configuration.

This PR also makes other CLIs make use of `cli_common.utils.create_dask_client`, introduced by #331, and gives this routine a docstring.

### CODE REVIEW

**Comment by neal-siekierski** [comment]
The build is failing due to timing out when trying to download `TCGA-02-0010-01Z-00-DX4.07de2e55-a8fe-40ee-9e98-bcb78050b9f7.svs` (https://travis-ci.org/DigitalSlideArchive/HistomicsTK/builds/233638236#L4995)

**Comment by manthey** [comment]
Let me see if we can use a subset of that file for the tests where we use it.

**Comment by neal-siekierski** [comment]
`web_client_HistomicsTK.annotations` has failed again. I'm going to rerun the build and see if it's just finicky.

**Comment by cdeepakroy** [comment]
You may have to delete the cache for the branch and restart the build.

**Comment by neal-siekierski** [comment]
Failure continues -- looking more closely, it's failing at the "open image" step in the setup for the web client test: https://travis-ci.org/DigitalSlideArchive/HistomicsTK/builds/236041568#L7711. I don't reproduce this locally, so I might look into reproducing Travis's setup (cf. https://stackoverflow.com/a/38804734) unless someone has a good idea of what might be going on. @jbeezley?

**Comment by jbeezley** [comment]
Locally, I'm seeing the same error about 25% of the time, but it could be higher on travis.  I'll see if I can fix it.

**Comment by neal-siekierski** [comment]
Okay, I've added a test for `cli_common.utils.splitArgs` (though it would be nice to somehow get coverage for the CLIs directly, though I know that's difficult) and I've fixed an intermittent test failure. PTAL.

**Pull request merged**
