### PR TITLE
Fix IndexError in simple_mask() if no peaks are found

### PR DESCRIPTION
**Pull request by hnakhoul**
If no peaks are found in the image histogram, the fallback definition of
TissuePeak throws an IndexError in Python 3. This commit addresses it by
converting the index to an integer.

### CODE REVIEW

**Comment by manthey** [comment]
@hnakhoul Is using item() better than asscalar?

**Comment by hnakhoul** [comment]
While trying it out I got a note saying that asscalar is deprecated (since np version 1.16) and to use item() instead.

Not sure the change takes care of every issue, but would be grateful for a fix for those of us running HistomicsTK on Python 3.

**Comment by manthey** [comment]
@hnakhoul Can you resolve the conflict I caused?  Once done, we'll merge this PR.  Thanks.

**Comment by kheffah** [comment]
The commit here was cherry-picked into [this PR](https://github.com/DigitalSlideArchive/HistomicsTK/pull/852), and conflicts resolved.

**Comment by kheffah** [comment]
The commit here was cherry-picked into [this PR](https://github.com/DigitalSlideArchive/HistomicsTK/pull/852), and conflicts resolved.

**Pull request closed without merging**
