### PR TITLE
Generic deploy playbook

### PR DESCRIPTION
**Pull request by zachmullen**
@dgutman what version of ubuntu are you attempting to deploy onto? That will affect how we have to set up our service scripts

### CODE REVIEW

**Comment by zachmullen** [comment]
@dgutman I added the debug statement and unset the PYTHONPATH in the deploy environment. Any other changes we should make, or is this good to go?

**Comment by manthey** [comment]
@zachmullen I used a clean Ubuntu 14.04 VM, and, when I run `./deploy_local.sh`, I get the error:
```
ERROR: girder is not a legal parameter in an Ansible task or handler
```

**Comment by zachmullen** [comment]
What version of Ansible are you using?

**Comment by manthey** [comment]
Odd -- I must have done something in different the last time.  I just repeated the steps (make a new ubuntu 14.04 VM; apt-get update; apt-get upgrade; follow steps in README, excepting to switch branch before run ./deploy_local.sh), and it is working just fine.

I think I had done `apt-get install ansible` the previous time (before running the steps in the readme, in the cavalier belief that I was going to need it).

**Comment by manthey** [comment]
The version of ansible that apt-get (on Ubuntu 14.04) installs is 1.5.4.  Via pip install it is 2.1.1.0.  Would it be worth it to add the -U flag to the in `sudo pip install ansible` line in the README?

**Comment by manthey** [comment]
Otherwise, LGTM.

**Comment by zachmullen** [comment]
I'll add the `-U` flag, good idea.

**Comment by manthey** [comment]
LGTM.

**Pull request merged**
