### PR TITLE
Large image integration

### PR DESCRIPTION
**Pull request by jbeezley**
This adds a simple control widget to select a Girder item to display.  Either a "large_image" item or an item containing an image file can be selected, and it will appear in the visualization panel rendered by GeoJS.

* It requires the latest master of the large_image plugin.
* The control widget will only let you select items under your user in Girder rather than an arbitrary collection.

### CODE REVIEW

**Comment by brianhelba** [comment]
Lets discuss this in-person tomorrow before merging.

**Comment by cdeepakroy** [comment]
@jbeezley Nice! I could get it to view a simple png image. But when i tried to view this [SVS image](https://data.kitware.com/#item/56b331718d777f5d6174259a) it throws an error.

large_image_integration

**Comment by jbeezley** [comment]
You probably need to initialize it first by posting to `/item/{itemId}/tiles`.

**Comment by brianhelba** [comment]
LGTM.

**Pull request merged**
