### PR TITLE
PEP8 renaming and refactoring of functions in color_deconvolution module

### PR DESCRIPTION
**Pull request by cdeepakroy**

### CODE REVIEW

**Comment by cdeepakroy** [comment]
@manthey Do you know what is causing this [error](https://travis-ci.org/DigitalSlideArchive/HistomicsTK/builds/185922007#L3945) in large_image? It only occurs on Travis

**Comment by jbeezley** [comment]
It looks like part of the hashing code that @brianhelba put in.  My first guess is some sort of openssl incompatibility, but I checked in a different branch and it is still 1.0.1f.  Perhaps the conda environment is bringing in some other openssl library.

For the record, this is the stack trace that occurs in every test that starts the server:
```python
Traceback (most recent call last):
  File "/home/travis/build/DigitalSlideArchive/HistomicsTK/build/girder/plugins/HistomicsTK/plugin_tests/docker_test.py", line 38, in setUpModule
    base.startServer()
  File "tests/base.py", line 56, in startServer
    server = setupServer(test=True, plugins=enabledPlugins)
  File "girder/utility/server.py", line 145, in setup
    root, appconf = configureServer(test, plugins, curConfig)
  File "girder/utility/server.py", line 115, in configureServer
    plugins, curConfig, ignoreMissing=True))
  File "girder/utility/plugin_utilities.py", line 114, in getToposortedPlugins
    allPlugins = findAllPlugins(curConfig)
  File "girder/utility/plugin_utilities.py", line 362, in findAllPlugins
    findEntryPointPlugins(allPlugins)
  File "girder/utility/plugin_utilities.py", line 328, in findEntryPointPlugins
    if pkg_resources.resource_exists(entry_point.name, configJson):
  File "/home/travis/build/DigitalSlideArchive/HistomicsTK/build/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1141, in resource_exists
    return get_provider(package_or_requirement).has_resource(resource_name)
  File "/home/travis/build/DigitalSlideArchive/HistomicsTK/build/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 426, in get_provider
    __import__(moduleOrReq)
  File "/home/travis/build/DigitalSlideArchive/HistomicsTK/build/miniconda/lib/python2.7/site-packages/large_image-0.2.0-py2.7.egg/large_image/__init__.py", line 21, in <module>
    from server import tilesource
  File "/home/travis/build/DigitalSlideArchive/HistomicsTK/build/miniconda/lib/python2.7/site-packages/large_image-0.2.0-py2.7.egg/large_image/server/tilesource/__init__.py", line 22, in <module>
    from .base import TileSource, getTileSourceFromDict, TileSourceException, \
  File "/home/travis/build/DigitalSlideArchive/HistomicsTK/build/miniconda/lib/python2.7/site-packages/large_image-0.2.0-py2.7.egg/large_image/server/tilesource/base.py", line 29, in <module>
    from girder.utility import assetstore_utilities
  File "girder/utility/assetstore_utilities.py", line 20, in <module>
    from .filesystem_assetstore_adapter import FilesystemAssetstoreAdapter
  File "girder/utility/filesystem_assetstore_adapter.py", line 33, in <module>
    from . import hash_state
  File "girder/utility/hash_state.py", line 99, in <module>
    initVectorFirstWord=b'\x01\x23\x45\x67\x89\xab\xcd\xef'
  File "girder/utility/hash_state.py", line 88, in __init__
    stateDataPointer = _getHashStateDataPointer(instance)
  File "girder/utility/hash_state.py", line 72, in _getHashStateDataPointer
    assert stateDataPointer
AssertionError
```

**Comment by cdeepakroy** [comment]
@manthey Can you please take a look at [this](https://travis-ci.org/DigitalSlideArchive/HistomicsTK/builds/194523474#L2472) error? It seems like npm install is failing. 

I already tried clearing the cache and restarting the build.

**Comment by manthey** [comment]
We merged the Girder 2 branch into large_image, but travis is using it in this build.

Change the large_image branch in .travis.yml to `girder-1.7`.

**Comment by manthey** [comment]
Ah, we also have to ask Conda not to use Python 2.7.13 because of a hashing change.  Change the conda update line in .travis.yml to:

```
   - conda update --yes --quiet --all 'python<=2.7.12'
```

**Pull request merged**
