### PR TITLE
casting image dtype for consistant scaling.

### LINKED ISSUE #1002: Single band nuclei detection should use consistent scaling across image
One of the reasons we want to calculate a whole-image scaling parameter is to avoid processing differences on different tiles.

### PR DESCRIPTION
**Pull request by subinkitware**
resolving this fixes #1002

### CODE REVIEW

**Comment by manthey** [comment]
Do you have a specific example where this changes the results?  That is, is there a test we can add or I can run locally to see the behavior change?

**Comment by subinkitware** [comment]
> Do you have a specific example where this changes the results? That is, is there a test we can add or I can run it locally to see the behavior change?

The additional casting doesn't change the results. I have tested a few RGB, Single channel, and multichannel images. All their `im_tile` array are already in `unint8` I'm not sure if we encounter float as an `im_tile` datatype in a WSL file. If it doesn't, we can remove this casting code.

**Comment by subinkitware** [comment]
> Do you have a specific example where this changes the results? That is, is there a test we can add or I can run locally to see the behavior change?

Inside the `detect_nuclei_with_dask` function there are already methods that check if it is a single channel/float datatype and converts the image accordingly. So I believe the data will be consistent in the case of single-channel images.  We might not need to add additional code for data consistency.

**Comment by subinkitware** [comment]
- I have used the large_image.getThumbnail() get generate a low-res image of the WSI to the size 1024

@manthey - The Cli `ComputeNucleiFeatures` also uses the mu and sigma calculation of the lab space for data processing. So, can I also make this similar updates on that files in this same PR?

**Comment by subinkitware** [comment]
A follow-up PR #1043 has been generated to abstract the nuclei detection code.

**Pull request closed without merging**
