### PR TITLE
JSON encode values passed back to the server

### LINKED ISSUE #95: Pass values of CLI parameters in json.dumps format while running a CLI through front-end
While running a CLI through the histomicstk front end (`localhost:808/histomicstk#<cli-name>`), pass values of CLI parameters in the POST Request are in the format outputted by `json.dumps`. I use `json.loads` to convert them back to a value of their python type.

### PR DESCRIPTION
**Pull request by jbeezley**
@cdeepakroy PTAL

Fixes #95

### CODE REVIEW

**Comment by cdeepakroy** [comment]
Just merged your changes into my branch and tested it. Still getting the same error. Do you want to hop on a hangout to debug it.

**Comment by cdeepakroy** [comment]
Shown below is the error:

> static/built/girder.app.min.js:4 500 Internal Server Error {"message": "ValueError: ValueError('No JSON object could be decoded',)", "trace": [["girder/api/rest.py", 428, "endpointDecorator", "val = fun(self, args, kwargs)"], ["girder/api/rest.py", 968, "POST", "return self.handleRoute(method, path, params)"], ["girder/api/rest.py", 742, "handleRoute", "val = handler(**kwargs)"], ["girder/api/rest.py", 273, "wrapped", "return fun(*args, **kwargs)"], ["girder/api/rest.py", 273, "wrapped", "return fun(*args, **kwargs)"], ["girder/api/rest.py", 273, "wrapped", "return fun(*args, **kwargs)"], ["girder/api/rest.py", 1017, "wrapped", "return fn(self.ctx, *args, **kwargs)"], ["girder/api/access.py", 68, "wrapped", "return args[0](*iargs, **ikwargs)"], ["/media/common/EmoryImageAnnotationPlatform/code/girder/srclnx/plugins/HistomicsTK/server/rest_slicer_cli.py", 699, "cliHandler", "containerArgs, hargs)"], ["/media/common/EmoryImageAnnotationPlatform/code/girder/srclnx/plugins/HistomicsTK/server/rest_slicer_cli.py", 459, "_addOptionalInputParamsToContainerArgs", "hargs['params'][param.name])"], ["/media/common/EmoryImageAnnotationPlatform/code/girder/srclnx/plugins/HistomicsTK/server/rest_slicer_cli.py", 438, "_getParamCommandLineValue", "cmdVal = str(json.loads(value))"], ["/home/cdeepakroy/anaconda/envs/emory/lib/python2.7/json/__init__.py", 339, "loads", "return _default_decoder.decode(s)"], ["/home/cdeepakroy/anaconda/envs/emory/lib/python2.7/json/decoder.py", 364, "decode", "obj, end = self.raw_decode(s, idx=_w(s, 0).end())"], ["/home/cdeepakroy/anaconda/envs/emory/lib/python2.7/json/decoder.py", 382, "raw_decode", "raise ValueError(\"No JSON object could be decoded\")"]], "type": "internal"}

How do i find out which parameter is causing this error?

**Comment by jbeezley** [comment]
Not that I don't believe you, but did you rerun `npm install`?  I added a pudb breakpoint to debug it.  I'll try running it from your branch.

**Comment by cdeepakroy** [comment]
Ahh i always forget that. Sorry! 

Just ran npm install. But the error still prevails. Let me put a print statement in [server/rest_slicer_cli/_getParamCommandLineValue](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/server/rest_slicer_cli.py#L434-L440) to see which parameter is causing this.

**Comment by cdeepakroy** [comment]
@jbeezley how do i print out the whole POST request it is making to the server?

I added a try/except (see [here](https://github.com/DigitalSlideArchive/HistomicsTK/blob/nuclei_segmentation_cli/server/rest_slicer_cli.py#L458-L466)) to see which parameter is causing the error. And it is a string-enumeration parameter. I think the value is being passed as `"hematoxylin"` instead of `'"hematoxylin"'`.

**Comment by cdeepakroy** [comment]
Looks like [JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) that you are using is converting to the right format. There is probably something else messing with it.

**Comment by cdeepakroy** [comment]
LGTM!

**Comment by jbeezley** [comment]
I apparently don't have access to merge PR's.

**Pull request merged**
